drop table if exists WEX_Document CASCADE;
drop table if exists WEX_ExchangeRate CASCADE; 
drop table if exists WEX_Expense CASCADE;
drop table if exists WEX_ExpenseType CASCADE; 
drop table if exists WEX_Payee CASCADE;
drop table if exists WEX_PayeeType CASCADE; 
drop table if exists WEX_Tag CASCADE; 
drop table if exists WEX_TransactionEntry CASCADE; 
drop table if exists WEX_TransactionEntry_WEX_Tag CASCADE; 
drop sequence if exists hibernate_sequence;
create sequence hibernate_sequence start with 1 increment by 1;
create table WEX_Document (id bigint not null, createdTS timestamp not null, modifiedTs timestamp, uid varchar(255) not null, version bigint, documentDate timestamp not null, fileName varchar(255) not null, expense_id bigint, primary key (id));
create table WEX_ExchangeRate (id bigint not null, createdTS timestamp not null, modifiedTs timestamp, uid varchar(255) not null, version bigint, date date, fee double, fixFee double, fromCurrencyCode varchar(3), rate double not null, toCurrencyCode varchar(3), institution_id bigint, primary key (id));
create table WEX_Expense (id bigint not null, createdTS timestamp not null, modifiedTs timestamp, uid varchar(255) not null, version bigint, accountingValue decimal(19,2) not null, currencyAmount decimal(19,2) not null, currencyCode varchar(3), date timestamp not null, description varchar(255), documentCount integer, externalReference varchar(255), exchangeRate_id bigint, expenseType_id bigint, payee_id bigint, primary key (id));
create table WEX_ExpenseType (id bigint not null, createdTS timestamp not null, modifiedTs timestamp, uid varchar(255) not null, version bigint, description varchar(255), name varchar(255), selectable boolean not null, primary key (id));
create table WEX_Payee (id bigint not null, createdTS timestamp not null, modifiedTs timestamp, uid varchar(255) not null, version bigint, address1 varchar(255), address2 varchar(255), address3 varchar(255), city varchar(255), countryCode varchar(255), extra varchar(255), iban varchar(255), name varchar(255), postalAccount varchar(255), postalBank varchar(255), prefix varchar(255), zip varchar(255), payeeType_id bigint, primary key (id));
create table WEX_PayeeType (id bigint not null, createdTS timestamp not null, modifiedTs timestamp, uid varchar(255) not null, version bigint, description varchar(255), name varchar(255), selectable boolean not null, primary key (id));
create table WEX_Tag (id bigint not null, createdTS timestamp not null, modifiedTs timestamp, uid varchar(255) not null, version bigint, description varchar(255), name varchar(255), selectable boolean not null, number integer, type integer not null, primary key (id));
create table WEX_TransactionEntry (id bigint not null, createdTS timestamp not null, modifiedTs timestamp, uid varchar(255) not null, version bigint, accountingBalance decimal(19,2), accountingOrder bigint, accountingValue decimal(19,2) not null, accountingYear integer, currencyAmount decimal(19,2) not null, factor integer not null, systemEntry boolean not null, expense_id bigint, primary key (id));
create table WEX_TransactionEntry_WEX_Tag (WEX_TransactionEntry_id bigint not null, tags_id bigint not null, primary key (WEX_TransactionEntry_id, tags_id));
alter table WEX_Document add constraint UK_5yertsmd40asympx4xf6u61n2 unique (uid);
alter table WEX_ExchangeRate add constraint UK_4mrj6ivnyhq91p0qvdls90ko9 unique (uid);
alter table WEX_Expense add constraint UK_3g9xbpf6kxodops7dpbhmcwch unique (uid);
alter table WEX_ExpenseType add constraint UK_4j93kwomo5830tkcghtdt6641 unique (uid);
alter table WEX_Payee add constraint UK_9ce2vywn504fhc3733ii308jj unique (uid);
alter table WEX_PayeeType add constraint UK_3ox14v12khxi30fvhvlo8iitr unique (uid);
alter table WEX_Tag add constraint UK_tmab68c4ew3iyhlwc8rjaw21x unique (uid);
alter table WEX_TransactionEntry add constraint UK_fuy123o2g19m1rx3fyec8fxy8 unique (uid);
alter table WEX_Document add constraint FK1pdge9qre1lgniaf7yobgjb2x foreign key (expense_id) references WEX_Expense;
alter table WEX_ExchangeRate add constraint FKfmj5ob8cqpi0fgxgmw98lblip foreign key (institution_id) references WEX_Payee;
alter table WEX_Expense add constraint FKrx7dlq1yn4jk3crjrpw5x3uuv foreign key (exchangeRate_id) references WEX_ExchangeRate;
alter table WEX_Expense add constraint FKi3umvcfbpsmi0sxh0bq9qrixq foreign key (expenseType_id) references WEX_ExpenseType;
alter table WEX_Expense add constraint FK5f6njddmg9b29df6v7sxqjwwr foreign key (payee_id) references WEX_Payee;
alter table WEX_Payee add constraint FK5dcf210fd8nny12ewen9hi28l foreign key (payeeType_id) references WEX_PayeeType;
alter table WEX_TransactionEntry add constraint FKlmnlduq5cyn0r5o6deuwcrseu foreign key (expense_id) references WEX_Expense on delete cascade;
alter table WEX_TransactionEntry_WEX_Tag add constraint FK8xv4ycc4ihpivm3gvywfe9u9i foreign key (tags_id) references WEX_Tag;
alter table WEX_TransactionEntry_WEX_Tag add constraint FKdwcj0kkm9qmbip0jmrtnfj7gs foreign key (WEX_TransactionEntry_id) references WEX_TransactionEntry;
