spring:
  devtools:
     livereload: 
       enabled: true 
  datasource:
    url: jdbc:h2:c:/tmp/db/wexpenses8-devyml;AUTO_SERVER=TRUE
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: false

logging:
  file:
    name: c:/tmp/logs/wexpenses8.log
  pattern:
    file: "%d [%t] %5p %c{1}:%L - %m%n"
    console: "%green(%d) [%t] %highlight(%-5level) %logger : %cyan(%msg%n)"
  level:
    org.springframework.web: DEBUG        

server:  
  port: 8090    
  max-http-header-size: 10000000
  servlet:
    context-path: /wexpenses8
  error:
    whitelabel:
      enabled: false

joinfaces:
  jsf:
    PROJECT_STAGE: Development

wexpenses:
  documents:
    url: ${server.servlet.context-path}/documents/{0,date,yyyy}/{1}
    root: ./
  currency-value:
    code: CHF
    precision: 0.05

---
spring:
  profiles: work
  datasource:
    url: jdbc:h2:C:/Users/willi/db/wexpenses-work-v2;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: none

---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:C:/Users/willi/Documents/wexpenses/wexdb/wexpenses-prod-v2;AUTO_SERVER=TRUE
  jpa:
    hibernate:
      ddl-auto: none
logging:
  file:
    name: C:/Users/willi/Documents/wexpenses/logs/wexpenses.log
wexpenses:
  documents:
    root: C:/Users/willi/Documents/wexpenses/documentstore