spring:
  devtools:
     livereload: 
       enabled: true 
  datasource:
    url: jdbc:h2:${wexpenses.base}/db/wexpenses-db;AUTO_SERVER=TRUE    
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: false

logging:
  pattern:
    console: "%green(%d) [%t] %highlight(%-5level) %logger : %cyan(%msg%n)"
  level:
    org.springframework.web: DEBUG        

server:  
  port: 8090    
  max-http-header-size: 10000000
  servlet:
    context-path: /wexpenses
  error:
    whitelabel:
      enabled: false

joinfaces:
  jsf:
    PROJECT_STAGE: Development

wexpenses:
  base: ${user.home}${server.servlet.context-path}
  documents:
    url: ${server.servlet.context-path}/documents/{0,date,yyyy}/{1}
    root: ${wexpenses.base}/documentstore/
  currency-value:
    code: CHF
    precision: 0.05

---
spring:
  profiles: createDb
  jpa:
    hibernate:
      ddl-auto: create-drop

---
spring:
  profiles: logFile
logging:
  file:
    name: ${wexpenses.base}/logs/wexpenses.log
  pattern:
    file: "%d [%t] %5p %c{1}:%L - %m%n"

---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:C:/Users/willi/Documents/wexpenses/wexdb/wexpenses-prod-v2;AUTO_SERVER=TRUE
wexpenses:
  documents:
    root: C:/Users/willi/Documents/wexpenses/documentstore
